#!/usr/bin/env php
<?php declare(strict_types=1);

/*
 * This file is a part of Caprice package
 *
 * @package     Caprice
 * @version     0.1.0
 * @author      Lotfio Lakehal <contact@lotfio.net>
 * @copyright   Lotfio Lakehal 2018
 * @license     MIT
 * @link        https://github.com/lotfio/caprice
 *
 */

use Caprice\Template;


require 'vendor/autoload.php';


$parser = new Template("test.cap.php");
$parser->generateParsedFile("index.php");